doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: "%kernel.debug%"
        use_savepoints: true
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
            app_ping_status: Heph\Infrastructure\Doctrine\Types\Ping\PingStatusType
            app_ping_message: Heph\Infrastructure\Doctrine\Types\Ping\PingMessageType
            app_lm_quatre_owner: Heph\Infrastructure\Doctrine\Types\LmQuatre\LmQuatreOwnerType
            app_lm_quatre_email: Heph\Infrastructure\Doctrine\Types\LmQuatre\LmQuatreEmailType
            app_shared_libelle: Heph\Infrastructure\Doctrine\Types\Shared\LibelleType
            app_shared_description: Heph\Infrastructure\Doctrine\Types\Shared\DescriptionType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Heph:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'Heph\Entity'
                alias: Heph
        controller_resolver:
            auto_mapping: false

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
