security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        users_in_db:
            entity:
                class: Heph\Entity\Users\Users
                property: username

    firewalls:
        api:
            pattern: ^/api
            stateless: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
